# Generated by Django 5.1.5 on 2025-02-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_blue_team_precent_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blue_team_precent',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='red_team_precent',
            field=models.PositiveIntegerField(),
        ),
    ]
