# Generated by Django 5.1.5 on 2025-02-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blue_team_precent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='red_team_precent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
