# Generated by Django 5.1.6 on 2025-03-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_blue_team_precent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='blue_team_precent',
            new_name='blue_team_percent',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='red_team_precent',
            new_name='red_team_percent',
        ),
    ]
