apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cybermaster-backend
  name: cybermaster-backend
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: cybermaster-backend
  type: NodePort
status:
  loadBalancer: {}
