apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: cybermaster-backend-ingress
spec:
  rules:
  - host: cybermaster.tech
    http:
      paths:
      - backend:
          service:
            name: backend-backend
            port:
              number: 8000
        path: /api
        pathType: Prefix
status:
  loadBalancer: {}