# Generated by Django 5.1.6 on 2025-04-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='cert_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
