# Generated by Django 5.1.6 on 2025-04-15 11:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_alter_certification_cert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
