# Generated by Django 5.1.6 on 2025-05-24 23:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0003_certification_date'),
        ('courses', '0004_enrollment_cert_ready'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='certification',
            unique_together={('course', 'user')},
        ),
    ]
