# Generated by Django 5.1.6 on 2025-04-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answer_examattempt_cert_ready_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(help_text='Format: HH:MM:SS (e.g., 01:30:00 for 1 hour and 30 minutes)'),
        ),
    ]
