# Generated by Django 5.1.6 on 2025-04-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='author_photo',
            field=models.FileField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='course',
            name='author_role',
            field=models.CharField(default='', max_length=255),
        ),
    ]
