# Generated by Django 5.1.6 on 2025-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_author_course_author_photo_course_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='cert_ready',
            field=models.BooleanField(default=False),
        ),
    ]
