# Generated by Django 5.1.6 on 2025-05-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_cert_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
