apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cybermaster_postgres
  name: cybermaster_postgres
spec:
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: cybermaster_postgres
  type: ClusterIP
status:
  loadBalancer: {}
