# Generated by Django 5.1.6 on 2025-04-11 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('connection_info', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=255, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='categories.category')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LabResourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='lab_resources/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='labs.lab')),
            ],
        ),
    ]
