# Generated by Django 5.1.6 on 2025-04-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='port',
            field=models.IntegerField(default=8443),
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
