# Generated by Django 5.1.6 on 2025-04-17 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='lesson',
        ),
    ]
