# Generated by Django 5.1.6 on 2025-04-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_remove_lab_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvedlab',
            old_name='solved_at',
            new_name='solved_on',
        ),
    ]
